logging:
  level:
    com:
      scotiabank:
        digital:
          factory: DEBUG
    org:
      springframework:
        r2dbc: DEBUG
spring:
  application:
    name: "digital-factory"
  r2dbc:
    url: r2dbc:h2:mem:///studentdb
    username: sa
    password:
  sql:
    init:
      mode: always
