DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
  ID VARCHAR(8) PRIMARY KEY,
  NOMBRE VARCHAR(10) NOT NULL,
  APELLIDO VARCHAR(30) NOT NULL,
  ESTADO VARCHAR(8) NOT NULL CHECK (ESTADO IN ('activo', 'inactivo')),
  EDAD INTEGER NOT NULL
);

INSERT INTO STUDENT (ID, NOMBRE, APELLIDO, ESTADO, EDAD)
VALUES ('72332211', 'Paúl', 'Guevara', 'activo', 28);
