DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
  ID VARCHAR(100) PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDO VARCHAR(100) NOT NULL,
  ESTADO BOOLEAN NOT NULL,
  EDAD INTEGER NOT NULL
);

INSERT INTO STUDENT (ID, NOMBRE, APELLIDO, ESTADO, EDAD)
VALUES ("72332211", 'Paúl', 'Guevara', TRUE, 28);
